---
output: pdf_document
---

# Acknowledgments {-}

Welcome to the, according to some, most important part of this thesis. I greatly appreciate you taking the time to read my thesis and now have arrived to this section.

Ola as my primary supervisor, you are probably the person that I have cost most time and energy. I found it valuable that you could always find the time if there was the need to talk about my projects where you nudged me in the right direction when I was stuck. I am thankful for your support and guidance throughout my studies.

Ivan, thank you for your co-supervision of my studies. Although you were on a different continent, you were always open for discussions about science to which you brought a hint of philosophy.  Your view on the projects was extremely valuable as it comes from a vastly different perspective than ours over here which enriches science immensely. Also, thank you for the opportunities to involve me in paper reviews as they were extremely fun and helpful.

Without a doubt research is not something that can be done alone, and this thesis would not have happened without collaboration between researchers. I have not met everyone with whom I share a space in the author lists of the research papers presented herein. However, I am extremely grateful for everyone’s contribution that enabled these studies. A special thanks goes to Christine Chio for involving us in the pancreatic cancer studies. I really enjoyed discussing and exploring the data with you. Furthermore, I would also like to thank everyone I worked with on projects that are not included in this thesis that contributed greatly to my development.

I would also like to take this opportunity to thank my opponent, Alessandro Quattrone and the examination board members, Lukas Käll, Arne Östman and Rickard Sandberg that have sacrificed their time and energy to examine my PhD studies.

I would also like to thank previous and current member of the Ola Larsson group; Laia, Vincent, Julie, Baila, Carl Murie, Shuo, Margaritha, Dong mei, Inci, Shan, Hui, Krzysztof, Kiana, Kathleen and Johannes. 
Laia, thank you for the peanut butter jelly times and for showing me around the cell lab it was extremely fun to work with you. Julie, I learned a great deal while working together with you. Vincent, you always had a positive attitude and open for discussing bioinformatics thank you for that. Margaritha, I will absolutely burn it.  Hui, thank you for discussions about science and showing me places that I must visit in China. It was nice sharing an office with you. Shan, it was refreshing to also talk about other things than science while at work, thank you for that. Inci, your engagement in science is inspiring I wish you all the best during you studies. Kathleen, I encourage you to keep putting things into the square hole. Krzyzstof, I was always looking forward to your monthly visits it was a blast working together with you. Kiana, it was great discussing science with you, you will do great in your studies. Johannes, suffering together through the process of finishing up our shared project makes it (yes, still not done) more bearable. Thank you for all your input and help it would not get done without you.

I also want to thank the members of the Rolny group; Sabrina, Yangxun and Charlotte I enjoyed our interactions. 

Lars Eijssen, I really appreciated your supervision during my bachelor project in BiGCaT. Working with you encouraged me to continue the bioinformatics path in science, which partly led me here.
 
While I enjoyed support and guidance from my supervisors, co-workers and collaborators in my professional career there were also numerous people that had a large influence on my sanity outside of my working environment.
 
Anne-Laure, while I only ever once made use of your mentorship you pretty well nailed it, thank you for that. I hope that we can grow a lot of vegetables in the allotment garden together soon.

Katharina and Alex, I really enjoy our interactions and nerf gun fights. Also, Katharina you will always have a special place in my heart for introducing the tree bark cheese to me.

John, thank you for your advice throughout the years and providing an environment full of humour (the right kind) when it was greatly needed. And of course, your networking skills should be noted.

Carl, Matthias, Irena, Kilian, Julia, Rickard, Christian, Naemi and Paula, I cannot be any happier to have such great climbing companions. I really like our group dynamic where we push each other’s limits in climbing. Training with you is always invigorating and helped me a lot to recharge!
I also want to thank Tom, Linda, Matthew, Nicole, Solmaz and Phillip you are great friends, and I am grateful to know you! It was extremely nice to get to travel with all of you and spend time together just relaxing.

Susanne, Antoine & Louise (AnSuLu), thank you for showing us around Switzerland and Nashville when we visited you there. I really hope we can soon meet up again.

Mam & Pap, ich danke euch für die undenliche Unterstützung die ich von euch bekomme in allem was ich tue. Tobias, danke für die tollen Spieleabende die wir zusammen verbracht haben, es ist toll so unseren Kontakt zu erhalten trotz der Ferne. Wie in alten Zeiten.  Sascha & Anna, ich hoffe bald eurer Paradis in der Eifel wieder besuchen zu können und freue mich Lotta kennen zu lernen. Kathrin, ich hoffe eines meiner Bücher findet einen Platz in eurem neuen Haus, ich bin ganz gespannt wie es wird!

To my partner Christina, nothing of this would have happened without getting to know you. Your support in everything along the way was, and always will be, invaluable. On a more personal note, I am grateful that I can call you my partner in life as in difficult times we bond together to face every obstacle, and in easier times we encourage each others complete and utter craziness.  I could not wish for anymore. 









